### ISSUE TITLE
Fix issue where “Testimonials” is appearing on a second line in the sub navigation

### ISSUE THREAD

**Issue by DEV-SOUTH** [DEVSOUTH/PG#1]
![screen shot 2017-10-09 at 12 30 03 pm](https://user-images.githubusercontent.com/7863309/31348443-a6c881fe-aced-11e7-83cc-4256067caa5f.png)

**Comment by tim0thius** [comment]
Cannot recreate this issue.

**Comment by tim0thius** [comment]
@DEV-SOUTH I reduced the padding between the nav items in an attempt to fix the wrapping issue. I can still not see the issue so please check it out and let me know if it is fixed.

**Comment by DEV-SOUTH** [comment]
It's still there. Don't stress on it. I will take a look with Phil when he has a minute since we can get in the same room

**Comment by DEV-SOUTH** [comment]
@nathanaelphilip can you see this issue? I still cannot add you as a participant.
