### ISSUE TITLE
Fix blog image “stretching” issue on the blog landing page”

### ISSUE THREAD

**Issue by DEV-SOUTH** [DEVSOUTH/PG#2]
Photos on the landing page appear stretched vertically.

![screen shot 2017-10-09 at 1 20 31 pm](https://user-images.githubusercontent.com/7863309/31350299-a5118480-acf4-11e7-947a-12ed085c9573.png)

**Comment by tim0thius** [comment]
Cannot recreate this issue.

**Comment by tim0thius** [comment]
@DEV-SOUTH Check this out on staging and let me know. http://staging.pg.flywheelsites.com/

**Comment by DEV-SOUTH** [comment]
nailed it.
