### ISSUE TITLE
Add “Performance Assessment” opt in button to the mobile menu.

### ISSUE THREAD

**Issue by DEV-SOUTH** [DEVSOUTH/PG#4]
This one is a bit more abstract so just see what you can do and let me know.

Ioanna attended an optimization conference and they stressed the importance of having an "opt-in" button on the mobile menu and that because the primary "sign up now" CTA goes away on mobile we only have the performance assessment button, which is way down the page. 

Can we either:

A) Get the primary CTA on the mobile menu

or

B) Bump up the performance assessment on mobile

![screen shot 2017-10-09 at 1 24 12 pm](https://user-images.githubusercontent.com/7863309/31350558-ab6fb8be-acf5-11e7-8a4e-73cde61f924b.png)

**Comment by tim0thius** [comment]
![image](https://user-images.githubusercontent.com/9800796/31558298-f44c6dba-b011-11e7-88ed-9bfa56e99658.png)
Will this work?

**Comment by DEV-SOUTH** [comment]
That's great
