### ISSUE TITLE
Staff photo replacement

### ISSUE THREAD

**Issue by DEV-SOUTH** [DEVSOUTH/PG#6]
please replace the photos photos of Ashley, Jason and Jack with the following (you will need to edit them to match what we've got on the page).

![img_1623](https://user-images.githubusercontent.com/7863309/31350744-54f19ac4-acf6-11e7-8407-fb67ba633dbb.JPG)
![img_1617](https://user-images.githubusercontent.com/7863309/31350746-54f3f8fa-acf6-11e7-9708-f94d307306f6.JPG)
![img_1600](https://user-images.githubusercontent.com/7863309/31350745-54f23038-acf6-11e7-915f-e9e118be513c.JPG)

**Comment by tim0thius** [comment]
@DEV-SOUTH Photos have been replaced.
