### ISSUE TITLE
New Coach Profile

### ISSUE THREAD

**Issue by DEV-SOUTH** [DEVSOUTH/PG#7]
Martina Xuereb, Performance Coach.

Martina has always been an avid sports person concentrating in athletics from an early age at which she competed at an international level for Malta mainly in 400m and relays in several events. Transferring her love of sports to her career was an easy step so she decided to move to London for her studies to later graduate with a BSc in Sports Science and MSc in Strength and Conditioning from Middlesex University as well as other coaching qualifications and sports massage therap, and is now in the last stages of achieving her UKSCA accreditation. During that time and after her studies Martina has had the opportunity to work in different sports and clubs such as British Fencing, Queens Park Rangers FC and Barnet and Southgate College Athletics Team and volunteer in a number at different sports clubs and schools. Although, Martina does not train to compete anymore she still enjoys doing a variety of sports such as running, lifting, tennis and yoga and is always up for trying out something different.

![img_1612](https://user-images.githubusercontent.com/7863309/31351349-bca896d4-acf8-11e7-81e0-af5bbe0a98c0.JPG)

**Comment by tim0thius** [comment]
@DEV-SOUTH Done.
