### ISSUE TITLE
new magazine feature callout

### ISSUE THREAD

**Issue by DEV-SOUTH** [DEVSOUTH/PG#8]
PG was featured on Men's Health magazine this month  -"The Best Gyms In The World". We need to find a way to show this on the homepage.

Maybe we could use our old bage in the top left of the "world class facility box"

**Comment by tim0thius** [comment]
@DEV-SOUTH If this works I can get it added back to the site
![image](https://user-images.githubusercontent.com/9800796/31625170-b19f661a-b26a-11e7-8e92-25a70346f48f.png)

**Comment by tim0thius** [comment]
@DEV-SOUTH I went ahead and added the old callout. If it doesn't work for whatever reason i can undo or tweak

**Comment by DEV-SOUTH** [comment]
Can we add as a subhead below Men's Health "The Best Gyms in the World"

edit: add this onto the red men's health badge

**Comment by tim0thius** [comment]
@DEV-SOUTH Let me know if this works. Looks a little too busy too me but not sure what else we can do without dumping a lot of time into it.
![image](https://user-images.githubusercontent.com/9800796/31676830-751b9a32-b32e-11e7-93ce-f3131f04e4b2.png)

**Comment by DEV-SOUTH** [comment]
This will work for now.
