### ISSUE TITLE
Text alignment on the About page issue

### ISSUE THREAD

**Issue by DEV-SOUTH** [DEVSOUTH/PG#9]
Text looks too high both on/off hover state

![screen shot 2017-10-16 at 5 54 25 pm](https://user-images.githubusercontent.com/7863309/31637106-27f72f70-b29b-11e7-9a24-913497f95924.png)

**Comment by tim0thius** [comment]
@DEV-SOUTH Added a fix. This is actually a problem for all pages that occurs when the browser window is really short. Its a little tricky because it behaves slightly different per section based on the number of lines the headline wraps to. Let me know if it works for you.

**Comment by DEV-SOUTH** [comment]
Still seeing the issue. I can look at this with Phil as well.

**Comment by nathanaelphilip** [comment]
@DEV-SOUTH it would help if you put the Browser & Version of the Browser in the issue. I don’t see this on Safari 11.0

**Comment by DEV-SOUTH** [comment]
Here it is @nathanaelphilip ... my bad I had shared it directly with Tim.

[export (1).pdf](https://github.com/DEV-SOUTH/PG/files/1391998/export.1.pdf)

**Comment by nathanaelphilip** [comment]
@DEV-SOUTH awesome – I think he said he figured it out. but just for future reference, it helps save a few minutes. also what your screen size is. (15" MacBook, etc)

**Comment by DEV-SOUTH** [comment]
10-4.
